"""Added all

Revision ID: 3ce32a0942e7
Revises: 92eec2a11aae
Create Date: 2018-03-15 20:34:59.040075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce32a0942e7'
down_revision = '92eec2a11aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'teams', ['LTeamID'], ['TeamID'])
        batch_op.create_foreign_key(None, 'seeds', ['Season'], ['Season'])
        batch_op.create_foreign_key(None, 'teams', ['WTeamID'], ['TeamID'])

    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'teams', ['TeamID'], ['TeamID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
