"""seeds

Revision ID: 92eec2a11aae
Revises: fb92d3471aac
Create Date: 2018-03-14 23:14:03.211546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eec2a11aae'
down_revision = 'fb92d3471aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Delta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('LFGP3_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('LFGP_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('LR_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('WFGP3_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('WFGP_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('WR_avg', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_matches_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('ix_teams_TeamID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('ix_teams_TeamID', ['TeamID'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_id', ['id'], unique=False)
        batch_op.drop_column('WR_avg')
        batch_op.drop_column('WFGP_avg')
        batch_op.drop_column('WFGP3_avg')
        batch_op.drop_column('LR_avg')
        batch_op.drop_column('LFGP_avg')
        batch_op.drop_column('LFGP3_avg')
        batch_op.drop_column('Delta')

    # ### end Alembic commands ###
