"""seeds

Revision ID: fb92d3471aac
Revises: 3abef1d84f4b
Create Date: 2018-03-14 23:04:43.704465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb92d3471aac'
down_revision = '3abef1d84f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Delta', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('Delta')

    # ### end Alembic commands ###
